apps:
  name     : 'test'
  script   : ./index.js
  instances: 2
  exec_mode: cluster
  autorestart: true
  watch: true
  restart_delay: 10000

  env_production:
    NODE_ENV: production
    NODE_PORT: 3232